source 'https://rubygems.org'

gem 'rails'
gem 'sqlite3'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem "dotenv-rails", require: "dotenv/rails-now"
gem "robinhood-ruby", path: "../.."

group :development, :test do
  gem 'pry'
  gem 'byebug'
end
